logging:
  level:
    com.amadeus.trip.*: INFO
    root: ERROR

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: trips

thread:
  pool:
    size: 10
    name: "ThreadPoolScheduler"

server:
  error:
    include-message: always
    include-binding-errors: always

quartz:
  properties:
    org.quartz.scheduler.instanceId: AUTO
    org.quartz.scheduler.instanceName: clusterName
    org.quartz.scheduler.jobFactory.class: org.quartz.simpl.SimpleJobFactory
    org.quartz.jobStore.class: com.novemberain.quartz.mongodb.MongoDBJobStore
    org.quartz.jobStore.mongoUri: mongodb://localhost:27017
    org.quartz.jobStore.dbName: trips
    org.quartz.jobStore.collectionPrefix: qrtz
    org.quartz.threadPool.threadCount: 1

